#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-2.0-or-later
"""Inspect and resolve the diff3 conflict markers left behind by apply_patch.py.

The overlay migration leaves ``<<<<<<< / ||||||| / ======= / >>>>>>>`` blocks in
``src/``. Resolving those by rewriting whole files is slow and dangerous, so this
module works at the granularity of a single conflict hunk.

A hunk has three sides. ``upstream`` is the new Blender text, ``ancestor`` is the
old Blender text the Mixar patch was written against, and ``mixar`` is the fork's
version.

Usage::

    python scripts/upgrade/conflicts.py report --src src --output report.md
    python scripts/upgrade/conflicts.py resolve --root . --decisions decisions.json
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

__all__ = ("main",)

START = "<<<<<<< "
ANCESTOR = "||||||| "
SEPARATOR = "======="
END = ">>>>>>> "

SKIP_DIRS = {".git", "__pycache__", ".mypy_cache"}


class Hunk:
    """One conflict block, as a half-open line range plus its three sides."""

    __slots__ = ("index", "start", "stop", "upstream", "ancestor", "mixar")

    def __init__(self, index, start, stop, upstream, ancestor, mixar):
        self.index = index
        self.start = start
        self.stop = stop
        self.upstream = upstream
        self.ancestor = ancestor
        self.mixar = mixar


def read_raw(path):
    """Read text without newline translation so CRLF files survive a round trip."""
    with open(path, "r", encoding="utf-8", newline="") as handle:
        return handle.read()


def write_raw(path, text):
    with open(path, "w", encoding="utf-8", newline="") as handle:
        handle.write(text)


def parse_conflicts(lines):
    """Return every conflict hunk found in ``lines`` (kept with line endings)."""
    hunks = []
    index = 0
    total = len(lines)
    while index < total:
        if not lines[index].startswith(START):
            index += 1
            continue
        start = index
        upstream, ancestor, mixar = [], [], []
        target = upstream
        seen_separator = False
        index += 1
        closed = False
        while index < total:
            line = lines[index]
            bare = line.rstrip("\r\n")
            if line.startswith(ANCESTOR) and not seen_separator:
                target = ancestor
            elif bare == SEPARATOR and not seen_separator:
                seen_separator = True
                target = mixar
            elif line.startswith(END):
                closed = True
                index += 1
                break
            else:
                target.append(line)
            index += 1
        if not closed:
            raise ValueError("unterminated conflict starting on line %d" % (start + 1))
        hunks.append(Hunk(len(hunks), start, index, upstream, ancestor, mixar))
    return hunks


def iter_conflicted(src):
    root = Path(src)
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        try:
            text = read_raw(path)
        except (OSError, UnicodeDecodeError):
            continue
        if START not in text:
            continue
        yield path, text


def fence(label, body, max_lines):
    shown = body[:max_lines]
    truncated = ", truncated from %d" % len(body) if len(body) > len(shown) else ""
    out = ["`%s` - %d line(s)%s\n\n" % (label, len(body), truncated), "```\n"]
    text = "".join(shown)
    out.append(text)
    if text and not text.endswith("\n"):
        out.append("\n")
    out.append("```\n\n")
    return out


def cmd_report(args):
    body = []
    file_count = 0
    hunk_count = 0
    for path, text in iter_conflicted(args.src):
        lines = text.splitlines(keepends=True)
        hunks = parse_conflicts(lines)
        if not hunks:
            continue
        file_count += 1
        hunk_count += len(hunks)
        body.append("## `%s`\n\n%d conflict(s)\n\n" % (path.as_posix(), len(hunks)))
        for hunk in hunks:
            body.append("### hunk %d, line %d\n\n" % (hunk.index, hunk.start + 1))
            body.extend(fence("upstream", hunk.upstream, args.max_lines))
            body.extend(fence("ancestor", hunk.ancestor, args.max_lines))
            body.extend(fence("mixar", hunk.mixar, args.max_lines))
    header = [
        "<!-- SPDX-FileCopyrightText: 2026 Mixar fork contributors -->\n",
        "<!-- SPDX-" "License-Identifier: GPL-3.0-or-later -->\n\n",
        "# Remaining overlay conflicts\n\n",
        "Generated by `scripts/upgrade/conflicts.py report`.\n\n",
        "- Files still carrying markers: %d\n" % file_count,
        "- Conflict hunks: %d\n\n" % hunk_count,
    ]
    if not file_count:
        header.append("Nothing left to resolve.\n\n")
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    write_raw(output, "".join(header + body))
    print("files=%d hunks=%d written to %s" % (file_count, hunk_count, output))
    return 0


def render(hunk, decision):
    """Turn one decision into the text that replaces a hunk.

    A decision is a side name, explicit ``{"text": ...}``, or a list of any of
    those concatenated in order. The list form exists because 5.2 frequently
    closes or opens ``namespace blender`` on the upstream side of a hunk whose
    Mixar side is an addition, so the two have to be emitted in a specific
    order that ``both`` cannot express.
    """
    if isinstance(decision, list):
        return "".join(render(hunk, item) for item in decision)
    if isinstance(decision, dict):
        if "text" in decision:
            text = decision["text"]
            if text and not text.endswith("\n"):
                text += "\n"
            return text
        decision = decision.get("side")
    if decision == "upstream":
        return "".join(hunk.upstream)
    if decision == "mixar":
        return "".join(hunk.mixar)
    if decision == "ancestor":
        return "".join(hunk.ancestor)
    if decision == "both":
        return "".join(hunk.upstream) + "".join(hunk.mixar)
    if decision == "drop":
        return ""
    raise ValueError("unknown decision: %r" % (decision,))


def is_single_decision(spec):
    if isinstance(spec, (str, list)):
        return True
    return isinstance(spec, dict) and ("text" in spec or "side" in spec)


def cmd_resolve(args):
    decisions = json.loads(read_raw(Path(args.decisions)))
    root = Path(args.root)
    applied = 0
    changed = 0
    problems = []
    for relative, spec in sorted(decisions.items()):
        if relative.startswith("$"):
            continue
        path = root / relative
        if not path.is_file():
            problems.append("%s: not found" % relative)
            continue
        lines = read_raw(path).splitlines(keepends=True)
        try:
            hunks = parse_conflicts(lines)
        except ValueError as error:
            problems.append("%s: %s" % (relative, error))
            continue
        if not hunks:
            print("%s: already clean, skipped" % relative)
            continue
        if is_single_decision(spec):
            chosen = {hunk.index: spec for hunk in hunks}
        else:
            chosen = {int(key): value for key, value in spec.items()}
        unknown = sorted(key for key in chosen if key >= len(hunks))
        if unknown:
            problems.append(
                "%s: decisions for missing hunks %s (file has %d)"
                % (relative, unknown, len(hunks))
            )
            continue
        pieces = []
        cursor = 0
        used = 0
        for hunk in hunks:
            if hunk.index not in chosen:
                continue
            pieces.append("".join(lines[cursor:hunk.start]))
            try:
                pieces.append(render(hunk, chosen[hunk.index]))
            except ValueError as error:
                problems.append("%s hunk %d: %s" % (relative, hunk.index, error))
                pieces = None
                break
            cursor = hunk.stop
            used += 1
        if pieces is None:
            continue
        pieces.append("".join(lines[cursor:]))
        write_raw(path, "".join(pieces))
        applied += used
        changed += 1
        remaining = len(hunks) - used
        note = ", %d left" % remaining if remaining else ""
        print("%s: resolved %d hunk(s)%s" % (relative, used, note))
    print("\napplied %d hunk(s) across %d file(s)" % (applied, changed))
    if problems:
        print("\nproblems:")
        for problem in problems:
            print("  " + problem)
        return 1
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    report = sub.add_parser("report", help="write a digest of every remaining conflict")
    report.add_argument("--src", default="src")
    report.add_argument("--output", default="docs/migration/conflicts-remaining.md")
    report.add_argument("--max-lines", type=int, default=60)
    report.set_defaults(func=cmd_report)

    resolve = sub.add_parser("resolve", help="apply a decisions file")
    resolve.add_argument("--root", default=".")
    resolve.add_argument("--decisions", default="scripts/upgrade/resolutions.json")
    resolve.set_defaults(func=cmd_resolve)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
