# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Mixar Configuration Utilities

Provides centralized configuration loading for all Mixar modules.
"""

import os
import json
import bpy

from .logging_config import get_logger

logger = get_logger(__name__)


UI_MODE_AI = "ai"
UI_MODE_PRO = "pro"
_UI_MODES = (UI_MODE_AI, UI_MODE_PRO)


def get_config_path():
    """Get the path to the config file"""
    return os.path.join(bpy.utils.resource_path('LOCAL'), 'config', 'mixar.json')


def load_mixar_config():
    """Load Mixar configuration from JSON file"""
    try:
        config_path = get_config_path()

        if os.path.exists(config_path):
            with open(config_path, 'r') as f:
                return json.load(f)
        else:
            logger.warning("Config file not found at: %s", config_path)
            return {}
    except Exception as e:
        logger.error("Error loading config: %s", e)
        return {}


# Global config instance
_config = None


def get_config():
    """Get the global configuration, loading it if necessary"""
    global _config
    if _config is None:
        _config = load_mixar_config()
    return _config

def add_config(key, value):
    """Add a key-value pair to the global configuration and persist to file"""
    global _config
    if _config is None:
        _config = load_mixar_config()
    _config[key] = value

    # Persist to file
    try:
        config_path = get_config_path()
        os.makedirs(os.path.dirname(config_path), exist_ok=True)
        with open(config_path, 'w') as f:
            json.dump(_config, f, indent=2)
        return True
    except Exception as e:
        logger.error("Error saving config: %s", e)
        return False


def get_environment():
    """Get the current environment from config"""
    config = get_config()
    return config.get('environment', 'Prod')


def get_server_url():
    """Get the API server URL (resolved at build time via env vars)."""
    config = get_config()
    return config.get('backend_url', 'https://api.mixar.app')


def get_dev_bypass_credentials() -> tuple:
    """Return (username, password) for dev bypass login, or ('', '') if disabled.

    Gated on a build-time constant in ``_build_env.py``, not on the mutable
    ``mixar.json``. The ``_build_env`` module is auto-generated by
    ``scripts/unix/build.sh`` / ``scripts/windows/build.bat`` and sets
    ``DEV_BYPASS_ALLOWED = True`` only for ``MIXAR_ENV=Dev`` builds. A user
    editing the bundled ``mixar.json`` to set ``environment=Dev`` cannot
    enable the bypass in a Prod/UAT build because the module that grants
    permission is not generated for those builds.

    Falls closed (returns ``('', '')``) when ``_build_env`` is absent - this
    is the case in source-tree imports (pytest, dev workflow before build).
    """
    try:
        from ._build_env import DEV_BYPASS_ALLOWED
    except ImportError:
        return ("", "")
    if not DEV_BYPASS_ALLOWED:
        return ("", "")
    config = get_config()
    bypass = config.get("dev_bypass", {})
    if not bypass.get("enabled", False):
        return ("", "")
    return (bypass.get("username", ""), bypass.get("password", ""))


def get_ui_mode() -> str:
    """Return the persisted UI mode. New users default to AI mode."""
    mode = get_config().get("ui_mode", UI_MODE_AI)
    return mode if mode in _UI_MODES else UI_MODE_AI


def set_ui_mode(mode: str) -> bool:
    """Persist the UI mode preference. Returns False on unknown mode or write failure."""
    if mode not in _UI_MODES:
        logger.error("Invalid ui_mode: %r", mode)
        return False
    return add_config("ui_mode", mode)


def get_frontend_url():
    """Get the frontend URL (resolved at build time via env vars).

    Used for browser-facing pages like SSO login.
    Falls back to the API server URL if frontend_url is not configured.
    """
    config = get_config()
    return config.get('frontend_url', get_server_url())
